[package]
name = "webhunt-derive"
version.workspace = true
edition.workspace= true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
deluxe.workspace = true
