[workspace]
resolver = "2"
members = ["webhunt", "webhunt-derive"]

[workspace.dependencies]
reqwest = "0.12.4"
scraper = "0.19.0"


# derive
proc-macro2 = "1"
quote = "1.0.40"
syn = "2.0"
deluxe = "0.5"
